#!/usr/bin/env bash
#
# build-pi5-image.sh — assemble an SD-card-ready Aegis boot directory for
# Raspberry Pi 5.
#
# This script produces `build/pi5-image/` containing every file the user
# needs to copy to the root of a freshly-formatted FAT32 SD card. It does
# NOT touch any block devices, does not need root, and is safe to run on
# any developer machine with network access.
#
# Prerequisites:
#   make -C kernel/arch/arm64 image    # produces kernel/arch/arm64/build/aegis.img
#
# Usage:
#   bash tools/build-pi5-image.sh
#
# Output:
#   build/pi5-image/
#     bootcode.bin            Pi firmware (legacy early bootloader)
#     start4.elf              Pi 4/5 GPU firmware (main stage)
#     fixup4.dat              memory pre-load config for start4.elf
#     start.elf               legacy GPU firmware (fallback)
#     fixup.dat               legacy memory config (fallback)
#     bcm2712-rpi-5-b.dtb     Pi 5 device tree (parsed by arch_mm.c)
#     config.txt              Aegis boot config (kernel_address=0x200000)
#     kernel8.img             renamed copy of build/aegis.img
#
# Firmware blobs are cached in references/pi-firmware/ so repeat runs are
# offline after the first fetch.
#
# STATUS: Pi 5 hardware boot is UNTESTED as of 2026-04-12. The GICv3
# driver work is in progress; a build with the current GICv2-only kernel
# will load and reach `[GIC] OK: GICv2 initialized` before freezing on
# Pi 5 silicon (GIC-600 is not GICv2-compatible). The image directory
# itself is correct either way; swapping in a GICv3-capable aegis.img is
# a one-file replacement of kernel8.img.

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
KERNEL_IMG="$REPO/kernel/arch/arm64/build/aegis.img"
FIRMWARE_CACHE="$REPO/references/pi-firmware"
OUT_DIR="$REPO/build/pi5-image"
FIRMWARE_BASE="https://github.com/raspberrypi/firmware/raw/master/boot"

FIRMWARE_FILES=(
    bootcode.bin
    start4.elf
    fixup4.dat
    start.elf
    fixup.dat
    bcm2712-rpi-5-b.dtb
)

# ── 1. Sanity check ──────────────────────────────────────────────────
if [ ! -f "$KERNEL_IMG" ]; then
    cat >&2 <<EOF
error: $KERNEL_IMG not found.

Build the ARM64 kernel image first:

    make -C kernel/arch/arm64 image

That produces build/aegis-arm64.elf and then wraps it in the Linux arm64
Image format as build/aegis.img. This script copies the result into the
Pi 5 boot directory as kernel8.img.
EOF
    exit 1
fi

# ── 2. Fetch firmware (cache in references/pi-firmware/) ─────────────
mkdir -p "$FIRMWARE_CACHE"
for f in "${FIRMWARE_FILES[@]}"; do
    dest="$FIRMWARE_CACHE/$f"
    if [ ! -s "$dest" ]; then
        echo ">>> downloading $f ..."
        if ! curl -L -f -o "$dest.tmp" "$FIRMWARE_BASE/$f"; then
            rm -f "$dest.tmp"
            cat >&2 <<EOF
error: failed to download $f from
  $FIRMWARE_BASE/$f

Check network connectivity and retry. If GitHub is unreachable you can
manually download the file from the upstream repo and drop it in:
  $FIRMWARE_CACHE/
then re-run this script.
EOF
            exit 1
        fi
        mv "$dest.tmp" "$dest"
    fi
    if [ ! -s "$dest" ]; then
        echo "error: cached firmware file $dest is empty" >&2
        exit 1
    fi
done

# ── 3. Produce build/pi5-image/ ──────────────────────────────────────
rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

for f in "${FIRMWARE_FILES[@]}"; do
    cp "$FIRMWARE_CACHE/$f" "$OUT_DIR/"
done

cat > "$OUT_DIR/config.txt" <<'CFG'
# Aegis Pi 5 boot config (generated by tools/build-pi5-image.sh)
#
# - arm_64bit=1              boot as aarch64, not 32-bit
# - kernel=kernel8.img       tells firmware which file to load as the kernel
# - device_tree=...          Pi 5 DTB; arch_mm.c parses it for RAM + GIC
# - kernel_address=0x200000  load kernel at physical 0x40200000
#                            (RAM_BASE 0x40000000 + 0x200000), matching
#                            KERN_LMA in kernel/arch/arm64/linker.ld
# - enable_uart=1            debug UART on GPIO 14/15 at 115200 8N1
# - uart_2ndstage=1          firmware prints its own boot banner to UART
# - disable_commandline_tags=1  don't append firmware cmdline args
arm_64bit=1
kernel=kernel8.img
device_tree=bcm2712-rpi-5-b.dtb
kernel_address=0x200000
enable_uart=1
uart_2ndstage=1
disable_commandline_tags=1
CFG

cp "$KERNEL_IMG" "$OUT_DIR/kernel8.img"

# ── 4. Summary + flash instructions ──────────────────────────────────
SIZE="$(du -sh "$OUT_DIR" | awk '{print $1}')"

cat <<EOF

================================================================
Aegis Pi 5 boot image ready: $OUT_DIR ($SIZE)
================================================================

Contents:
$(cd "$OUT_DIR" && ls -1 | sed 's/^/  /')

To flash to an SD card:

  1. Format an SD card as FAT32 (single partition covering the card).
     macOS:
       diskutil eraseDisk FAT32 AEGISBOOT MBRFormat /dev/diskN
     Linux:
       sudo parted /dev/sdX mklabel msdos
       sudo parted /dev/sdX mkpart primary fat32 1MiB 100%
       sudo mkfs.vfat -F 32 -n AEGISBOOT /dev/sdX1

  2. Copy every file from $OUT_DIR/ to the root of the SD card:
       cp -v $OUT_DIR/* /Volumes/AEGISBOOT/         # macOS
       cp -v $OUT_DIR/* /mnt/aegisboot/ && sync     # Linux

  3. Eject the SD card cleanly and insert it into the Pi 5.

  4. Wire up a USB-TTL serial adapter to the Pi 5 GPIO header:

       Pi 5 GPIO header (physical pins, board top edge):
         pin  1  3.3V       pin  2  5V
         pin  3  GPIO 2     pin  4  5V
         pin  5  GPIO 3     pin  6  GND     <-- cable GND (black)
         pin  7  GPIO 4     pin  8  GPIO 14 (TXD)  <-- cable RXD (white)
         pin  9  GND        pin 10  GPIO 15 (RXD)  <-- cable TXD (green)

     DO NOT connect the 5V/3.3V (red) wire from the USB-TTL adapter
     — the Pi is self-powered from its USB-C port. Only connect GND,
     Pi-TX -> cable-RX, Pi-RX -> cable-TX.

  5. Open a serial terminal at 115200 8N1:
       macOS:  screen /dev/tty.usbserial-* 115200
       Linux:  screen /dev/ttyUSB0 115200
               (or: minicom -b 115200 -o -D /dev/ttyUSB0)

  6. Power the Pi 5 (USB-C). You should see:

       Raspberry Pi ... firmware banner ...
       [SERIAL] OK: PL011 UART initialized
       [PMM] OK: ...
       [GIC] OK: GICv3 initialized        <-- GICv3 driver required
       [TIMER] OK: ...
       [SCHED] OK: scheduler started, N tasks
       vigil: starting
       ...

Notes:
  - Pi 5 hardware boot is UNTESTED as of 2026-04-12. If the kernel was
    built before the GICv3 driver (ARM64.md §17.2) landed, the boot will
    stop at "[GIC] OK: GICv2 initialized" because GIC-600 is not
    GICv2-compatible. Rebuild with the GICv3-capable kernel and rerun
    this script — kernel8.img is the only file that changes.
  - Firmware blobs are cached in $FIRMWARE_CACHE
    so subsequent runs are offline.

EOF
