#include "proc.h"
#include "elf.h"
#include "vmm.h"
#include "pmm.h"
#include "printk.h"
#include "arch.h"
#include <stdint.h>
#include <stddef.h>

_Static_assert(offsetof(aegis_process_t, task) == 0,
               "aegis_process_t: task must be at offset 0 for safe cast");

/*
 * init_elf / init_elf_len — generated by:
 *   cd user/init && xxd -i init.elf > init_bin.c
 * which produces exactly these symbol names when invoked as "xxd -i init.elf".
 */
extern const unsigned char init_elf[];
extern const unsigned int  init_elf_len;

/* 4KB kernel stack for the user process (single page) */
#define STACK_SIZE  4096UL

/*
 * KSTACK_VA — fixed higher-half virtual address for the user process kernel stack.
 *
 * The kernel's higher-half mapping covers [0xFFFFFFFF80000000, 0xFFFFFFFF80400000)
 * via 2MB huge pages.  We place the user kernel stack immediately above this range,
 * mapping a single 4KB page at 0xFFFFFFFF80400000 via vmm_map_page().
 *
 * Because vmm_map_page() adds PTE entries under the shared pdpt_hi PDPT page
 * (index 510 in PML4[511]), this mapping is visible in BOTH the master PML4 and
 * every user-process PML4 created by vmm_create_user_pml4().  That property is
 * required so that:
 *   (a) ctx_switch can access the kernel stack via this VA regardless of which
 *       PML4 is active (master or user), and
 *   (b) TSS.rsp0 (set to KSTACK_VA + STACK_SIZE) is a valid virtual address in
 *       the user PML4, allowing the CPU to deliver ring-3 interrupts.
 *
 * Phase 5 constraint: single user process only.  A multi-process design must
 * allocate a distinct kernel-stack VA for each process (e.g. via a VA allocator).
 */
#define KSTACK_VA   0xFFFFFFFF80400000ULL

/*
 * User stack layout:
 *   top = USER_STACK_TOP  (= 0x7FFFFFFF000, 16-byte aligned)
 *   page = [USER_STACK_PAGE, USER_STACK_TOP)
 * 0x7FFFFFFF000 ends in 0x000 — 4096-byte aligned → 16-byte aligned. ✓
 * Per AMD64 ABI, RSP on entry to _start must be 16-byte aligned.
 */
#define USER_STACK_TOP  0x7FFFFFFF000ULL
#define USER_STACK_PAGE (USER_STACK_TOP - 4096ULL)

/* Exported from syscall_entry.asm — a bare iretq, NOT a C function.
 * proc_spawn uses its address only as a return-address slot in the
 * initial kernel stack frame. */
extern void proc_enter_user(void);

void
proc_spawn(const uint8_t *elf_data, size_t elf_len)
{
    /* Allocate process control block (one PMM page) */
    uint64_t tcb_phys = pmm_alloc_page();
    if (!tcb_phys) {
        printk("[PROC] FAIL: OOM allocating process TCB\n");
        for (;;) {}
    }
    aegis_process_t *proc = (aegis_process_t *)(uintptr_t)tcb_phys;

    /* Allocate kernel stack (single 4KB page) and map it at a fixed higher-half
     * virtual address shared by both the master PML4 and all user PML4s.
     *
     * IDENTITY MAP DEPENDENCY: kstack_phys is a physical address returned by
     * pmm_alloc_page().  We pass it to vmm_map_page() which walks the master PML4
     * via phys_to_table() — valid only while the identity window [0..4MB) is live.
     *
     * After vmm_map_page() the kernel stack is accessible at KSTACK_VA in both
     * the master PML4 and the user PML4 (shared pdpt_hi PDPT page).  We then
     * use KSTACK_VA (not kstack_phys) for all subsequent pointer arithmetic so
     * the stack is reachable regardless of which PML4 is loaded in CR3. */
    uint64_t kstack_phys = pmm_alloc_page();
    if (!kstack_phys) {
        printk("[PROC] FAIL: OOM allocating kernel stack\n");
        for (;;) {}
    }
    vmm_map_page(KSTACK_VA, kstack_phys,
                 VMM_FLAG_PRESENT | VMM_FLAG_WRITABLE);
    uint8_t *kstack = (uint8_t *)KSTACK_VA;

    /* Create per-process page tables (kernel high entries shared) */
    proc->pml4_phys = vmm_create_user_pml4();

    /* Load ELF into the user address space */
    uint64_t entry_rip = elf_load(proc->pml4_phys, elf_data, elf_len);
    if (!entry_rip) {
        printk("[PROC] FAIL: ELF parse error\n");
        for (;;) {}
    }

    /* Allocate and map user stack page */
    uint64_t user_stack_phys = pmm_alloc_page();
    if (!user_stack_phys) {
        printk("[PROC] FAIL: OOM allocating user stack\n");
        for (;;) {}
    }
    vmm_map_user_page(proc->pml4_phys, USER_STACK_PAGE, user_stack_phys,
                      VMM_FLAG_PRESENT | VMM_FLAG_USER | VMM_FLAG_WRITABLE);

    /*
     * Build initial kernel stack.
     *
     * ctx_switch pops: r15, r14, r13, r12, rbp, rbx, then ret.
     * The ret target is proc_enter_user (a bare iretq label).
     * iretq pops a ring-3 frame: RIP, CS, RFLAGS, RSP, SS.
     *
     * Stack layout from low (RSP) to high:
     *   [r15=0][r14=0][r13=0][r12=0][rbp=0][rbx=0]
     *   [proc_enter_user]
     *   [entry_rip][CS=0x23][RFLAGS=0x202][user_RSP][SS=0x1B]
     *
     * Push order (high-to-low, decrementing sp):
     *   SS first (highest address), r15 last (lowest = task.rsp value).
     */
    uint64_t *sp = (uint64_t *)(kstack + STACK_SIZE);

    *--sp = 0x1BULL;            /* SS  — user data | RPL=3       */
    *--sp = USER_STACK_TOP;     /* RSP — user stack top           */
    *--sp = 0x202ULL;           /* RFLAGS — IF=1, reserved bit 1  */
    *--sp = 0x23ULL;            /* CS  — user code | RPL=3        */
    *--sp = entry_rip;          /* RIP — ELF entry point          */

    /*
     * User PML4 physical address: popped by proc_enter_user before iretq.
     * proc_enter_user does: pop rax; mov cr3, rax; iretq.
     * This switches CR3 to the user PML4 while still on the higher-half
     * kernel stack (KSTACK_VA — accessible in both master and user PML4).
     *
     * We must switch CR3 here rather than before ctx_switch in sched_tick
     * because sched_tick runs on the outgoing task's physical kernel stack
     * (accessible only via the identity map in the master PML4).  Switching
     * to the user PML4 from that stack would remove the identity map,
     * causing a triple fault on the next stack access (stack is not
     * mapped in the user PML4).
     */
    *--sp = proc->pml4_phys;    /* user PML4 phys — popped by proc_enter_user */

    *--sp = (uint64_t)(uintptr_t)proc_enter_user; /* ret → CR3 switch + iretq */
    *--sp = 0;                  /* rbx */
    *--sp = 0;                  /* rbp */
    *--sp = 0;                  /* r12 */
    *--sp = 0;                  /* r13 */
    *--sp = 0;                  /* r14 */
    *--sp = 0;                  /* r15 ← task.rsp */

    /* Initialize task fields */
    proc->task.rsp              = (uint64_t)(uintptr_t)sp;
    proc->task.stack_base       = kstack;
    proc->task.kernel_stack_top = (uint64_t)(uintptr_t)(kstack + STACK_SIZE);
    proc->task.tid              = 0xFF;   /* fixed user-process TID for Phase 5 */
    proc->task.is_user          = 1;

    sched_add(&proc->task);
}

void
proc_spawn_init(void)
{
    proc_spawn(init_elf, (size_t)init_elf_len);
}
